export const APP_NAME = 'CV Builder';

export const NAV_LIST = [
  {
    title: 'resumeTemplates',
    path: 'Home',
  },
  {
    title: 'resumeWritingService',
    path: 'Home',
  },
  {
    title: 'pricing',
    path: 'Home',
  },
  {
    title: 'contact',
    path: 'Home',
  },
  {
    title: 'login',
    path: 'Home',
  },
];
export const FEATURE_LIST = [
  {
    icon: '/img/rating.svg',
    title: 'feature1.title',
    description: 'feature1.description',
  },
  {
    icon: '/img/profiles.svg',
    title: 'feature2.title',
    description: 'feature2.description',
  },
  {
    icon: '/img/recruitment.svg',
    title: 'feature3.title',
    description: 'feature3.description',
  },
];

export const TESTIMONY_LIST = [
  {
    avatar: '/img/user-1.jpg',
    name: 'Dylan',
    description: 'testimony1.description',
    function: 'testimony1.function',
    rating: 5,
  },
  {
    avatar: '/img/user-2.jpg',
    name: 'Jay',
    description: 'testimony2.description',
    function: 'testimony2.function',
    rating: 5,
  },
  {
    avatar: '/img/user-3.jpg',
    name: 'Kate',
    description: 'testimony3.description',
    function: 'testimony3.function',
    rating: 5,
  },
];

export const COMPANY_LIST = [
  '/img/apple.svg',
  '/img/google.svg',
  '/img/nike.svg',
];

export const FAQ_LIST = [
  {
    question: 'What is a CV or resume?',
    answer:
      "CV or resume is an abbreviation of the Latin words 'curriculum vitae', which mean 'life course'. A professional resume provides a summary and a good overview of someone's life.Your resume includes your education(s) and qualifications, work experience, skills, and important qualities. By means of your resume, your potential employer will be able to get a good picture of your skills, work experience, and knowledge quickly, to assess whether or not you fit the job, and therefore whether to offer you a job interview.",
  },
  {
    question: 'What is a CV or resume?',
    answer:
      "CV or resume is an abbreviation of the Latin words 'curriculum vitae', which mean 'life course'. A professional resume provides a summary and a good overview of someone's life.Your resume includes your education(s) and qualifications, work experience, skills, and important qualities. By means of your resume, your potential employer will be able to get a good picture of your skills, work experience, and knowledge quickly, to assess whether or not you fit the job, and therefore whether to offer you a job interview.",
  },
  {
    question: 'What should I include in my curriculum vitae?',
    answer:
      'Your resume should only contain information relevant to your potential employer. So that means, what should be in your resume can differ per application. However, the bare minimum of details on your resume should at least include;',
  },
];

export const TEXT_INPUT_PROPS = [
  'placeholder',
  'label',
  'containerClass',
  'labelClass',
  'formControlClass',
  'id',
  'errorText',
];

// export const FORM_SCHEMA = [
//   {
//     fieldType: 'TextInput',
//     placeholder: 'First Name',
//     label: 'First Name',
//     name: 'firstName',
//     errorText: 'This is error',
//     containerClass: 'p-col-12',
//   },
//   {
//     fieldType: 'EditorInput',
//     label: 'Description',
//     name: 'description',
//     containerClass: 'p-col-12',
//   },
//   {
//     fieldType: 'DropdownInput',
//     label: 'Gender',
//     name: 'gender',
//     options: [
//       { label: 'Male', value: 'Male' },
//       { label: 'Female', value: 'Female' },
//       { label: 'Other', value: 'Other' },
//     ],
//     placeholder: 'gender',
//     containerClass: 'p-col-12',
//   },
//   {
//     fieldType: 'ChipsInput',
//     label: 'Hobbies',
//     name: 'hobbies',
//     containerClass: 'p-col-12',
//   },
// ];
const START_MONTH = [
  { label: "Don't Show", value: "Don't Show" },
  { label: 'Show Year Only', value: 'Show Year Only' },
  { label: 'January', value: 'January' },
  { label: 'February', value: 'February' },
  { label: 'March', value: 'March' },
  { label: 'April', value: 'April' },
  { label: 'May', value: 'May' },
  { label: 'June', value: 'June' },
  { label: 'July', value: 'July' },
  { label: 'August', value: 'August' },
  { label: 'September', value: 'September' },
  { label: 'October', value: 'October' },
  { label: 'November', value: 'November' },
  { label: 'December', value: 'December' },
];
const YEAR_LIST = [
  { label: '1960', value: '1960' },
  { label: '1961', value: '1961' },
  { label: '1962', value: '1962' },
  { label: '1963', value: '1963' },
  { label: '1964', value: '1964' },
  { label: '1965', value: '1965' },
  { label: '1966', value: '1966' },
  { label: '1967', value: '1967' },
  { label: '1968', value: '1968' },
  { label: '1969', value: '1969' },
  { label: '1970', value: '1970' },
  { label: '1971', value: '1971' },
  { label: '1972', value: '1972' },
  { label: '1973', value: '1973' },
  { label: '1974', value: '1974' },
  { label: '1975', value: '1975' },
  { label: '1976', value: '1976' },
  { label: '1977', value: '1977' },
  { label: '1978', value: '1978' },
  { label: '1979', value: '1979' },
  { label: '1980', value: '1980' },
  { label: '1981', value: '1981' },
  { label: '1982', value: '1982' },
  { label: '1983', value: '1983' },
  { label: '1984', value: '1984' },
  { label: '1985', value: '1985' },
  { label: '1986', value: '1986' },
  { label: '1987', value: '1987' },
  { label: '1988', value: '1988' },
  { label: '1989', value: '1989' },
  { label: '1990', value: '1990' },
  { label: '1991', value: '1991' },
  { label: '1992', value: '1992' },
  { label: '1993', value: '1993' },
  { label: '1994', value: '1994' },
  { label: '1995', value: '1995' },
  { label: '1996', value: '1996' },
  { label: '1997', value: '1997' },
  { label: '1998', value: '1998' },
  { label: '1999', value: '1999' },
  { label: '2000', value: '2000' },
  { label: '2001', value: '2001' },
  { label: '2002', value: '2002' },
  { label: '2003', value: '2003' },
  { label: '2004', value: '2004' },
  { label: '2005', value: '2005' },
  { label: '2006', value: '2006' },
  { label: '2007', value: '2007' },
  { label: '2008', value: '2008' },
  { label: '2009', value: '2009' },
  { label: '2010', value: '2010' },
  { label: '2011', value: '2011' },
  { label: '2012', value: '2012' },
  { label: '2013', value: '2013' },
  { label: '2014', value: '2014' },
  { label: '2015', value: '2015' },
  { label: '2016', value: '2016' },
  { label: '2017', value: '2017' },
  { label: '2018', value: '2018' },
  { label: '2019', value: '2019' },
  { label: '2020', value: '2020' },
  { label: '2021', value: '2021' },
  { label: '2022', value: '2022' },
  { label: '2023', value: '2023' },
  { label: '2024', value: '2024' },
  { label: '2025', value: '2025' },
  { label: '2026', value: '2026' },
  { label: '2027', value: '2027' },
  { label: '2028', value: '2028' },
  { label: '2029', value: '2029' },
  { label: '2030', value: '2030' },
];
const END_MONTH = [
  { label: 'Present', value: 'Present' },
  { label: "Don't Show", value: "Don't Show" },
  { label: 'Show Year Only', value: 'Show Year Only' },
  { label: 'January', value: 'January' },
  { label: 'February', value: 'February' },
  { label: 'March', value: 'March' },
  { label: 'April', value: 'April' },
  { label: 'May', value: 'May' },
  { label: 'June', value: 'June' },
  { label: 'July', value: 'July' },
  { label: 'August', value: 'August' },
  { label: 'September', value: 'September' },
  { label: 'October', value: 'October' },
  { label: 'November', value: 'November' },
  { label: 'December', value: 'December' },
];
export const FORM_SCHEMA = [
  // {
  //   fieldType: 'FileUploader',
  //   name: 'fileUploader',
  //   containerClass: 'p-col-12 p-mb-2',
  // },
  {
    fieldType: 'TextInput',
    label: 'First Name',
    name: 'firstName',
    containerClass: 'p-col-12 p-md-6',
  },
  {
    fieldType: 'TextInput',
    label: 'Last Name',
    name: 'lastName',
    containerClass: 'p-col-12 p-md-6',
  },
  {
    fieldType: 'TextInput',
    label: 'Email',
    name: 'email',
    containerClass: 'p-col-12 p-md-6',
  },
  {
    fieldType: 'TextInput',
    label: 'Phone number',
    name: 'phoneNumber',
    containerClass: 'p-col-12 p-md-6',
  },
  {
    fieldType: 'TextInput',
    label: 'Address',
    name: 'address',
    containerClass: 'p-col-12',
  },
  {
    fieldType: 'TextInput',
    label: 'Zip Code',
    name: 'zipCode',
    containerClass: 'p-col-12 p-md-6',
  },
  {
    fieldType: 'TextInput',
    label: 'City/Town',
    name: 'city',
    containerClass: 'p-col-12 p-md-6',
  },
];
export const FORM_EXPERIENCE_SCHEMA = [
  {
    title: 'Resume objective',
    iconClass: 'fa fa-user p-mr-2',
    name: 'resumeObjective',
    schemas: [
      {
        name: 'description',
        fieldType: 'EditorInput',
        label: 'Description',
        containerClass: 'p-col-12',
      },
    ],
  },
  {
    title: 'Work experience',
    iconClass: 'fa fa-suitcase p-mr-2',
    name: 'workExperience',
    isAdd: true,
    schemas: [
      {
        name: 'jobTitle',
        fieldType: 'TextInput',
        label: 'Job Title',
        placeholder: 'e. g. Sales Manger',
        containerClass: 'p-col-6',
      },
      {
        name: 'cityTitle',
        fieldType: 'TextInput',
        label: 'City/Town',
        placeholder: 'e. g. Sales Manger',
        containerClass: 'p-col-6',
      },
      {
        name: 'employer',
        fieldType: 'TextInput',
        label: 'Employer',
        placeholder: 'e. g. PwC',
        containerClass: 'p-col-12',
      },
      {
        fieldType: 'DropdownInput',
        label: 'Start Date',
        name: 'startMonth',
        options: START_MONTH,
        placeholder: "Don't Show",
        containerClass: 'p-col-6',
      },
      {
        fieldType: 'DropdownInput',
        name: 'startYear',
        options: YEAR_LIST,
        containerClass: 'p-col-6 p-as-end',
      },
      {
        fieldType: 'DropdownInput',
        label: 'End Date',
        name: 'endMonth',
        options: END_MONTH,
        placeholder: "Don't Show",
        containerClass: 'p-col-6',
      },
      {
        fieldType: 'DropdownInput',
        name: 'endYear',
        options: YEAR_LIST,
        containerClass: 'p-col-6 p-as-end',
      },
      {
        fieldType: 'EditorInput',
        label: 'Description',
        name: 'workDescription',
        containerClass: 'p-col-12',
      },
    ],
  },
  {
    title: 'Education and Qualifications',
    iconClass: 'fa fa-graduation-cap p-mr-2',
    name: 'education',
    schemas: [
      {
        name: 'degreeTitle',
        fieldType: 'TextInput',
        label: 'Degree',
        placeholder: 'e. g. Bachelor of Science',
        containerClass: 'p-col-6',
      },
      {
        name: 'schoolCityTitle',
        fieldType: 'TextInput',
        label: 'City/Town',
        placeholder: 'e. g. San francisco',
        containerClass: 'p-col-6',
      },
      {
        name: 'school',
        fieldType: 'TextInput',
        label: 'School',
        placeholder: 'e. g. New York University',
        containerClass: 'p-col-12',
      },
      {
        fieldType: 'DropdownInput',
        label: 'Start Date',
        name: 'startMonth',
        options: START_MONTH,
        placeholder: "Don't Show",
        containerClass: 'p-col-6 p-md-3',
      },
      {
        fieldType: 'DropdownInput',
        name: 'startYear',
        options: YEAR_LIST,
        value: '2021',
        containerClass: 'p-col-6 p-md-3 p-as-end',
      },
      {
        fieldType: 'DropdownInput',
        name: 'endMonth',
        options: END_MONTH,
        placeholder: "Don't Show",
        label: 'End Date',
        containerClass: 'p-col-6 p-md-3 p-as-end',
      },
      {
        fieldType: 'DropdownInput',
        name: 'endYear',
        options: YEAR_LIST,
        value: '2021',
        containerClass: 'p-col-6 p-md-3 p-as-end',
      },
      {
        fieldType: 'EditorInput',
        label: 'Description',
        name: 'schoolDescription',
        containerClass: 'p-col-12',
      },
    ],
  },
  {
    title: 'Interests',
    iconClass: 'fa fa-paint-brush p-mr-2',
    name: 'interests',
    schemas: [
      {
        fieldType: 'ChipsInput',
        label: 'Hobbies',
        name: 'hobbies',
        containerClass: 'p-col-12',
      },
    ],
  },
  {
    title: 'Skills',
    iconClass: 'fa fa-laptop p-mr-2',
    name: 'skills',
    schemas: [
      {
        fieldType: 'TextInput',
        placeholder: 'e.g Microsoft Word',
        label: 'Skill',
        name: 'skill',
        containerClass: 'p-col-6',
      },
      {
        fieldType: 'DropdownInput',
        label: 'Level',
        name: 'skillLevel',
        options: [
          { label: 'Expert', value: 'Expert' },
          { label: 'Experienced', value: 'Experienced' },
          { label: 'Skillful', value: 'Skillful' },
          { label: 'Intermediate', value: 'Intermediate' },
          { label: 'Beginner', value: 'Beginner' },
        ],
        placeholder: 'Select Level',
        containerClass: 'p-col-6',
      },
    ],
  },
  {
    title: 'Languages',
    iconClass: 'fa fa-globe p-mr-2',
    name: 'languages',
    schemas: [
      {
        fieldType: 'TextInput',
        placeholder: 'e.g. Spanish',
        label: 'Language',
        name: 'language',
        containerClass: 'p-col-6',
      },
      {
        fieldType: 'DropdownInput',
        label: 'Level',
        name: 'languageLevel',
        options: [
          { label: 'Select', value: 'Select' },
          { label: 'Native Speaker ', value: 'Native Speaker ' },
          { label: 'Experienced', value: 'Experienced' },
          { label: 'Skillful', value: 'Skillful' },
          { label: 'Intermediate', value: 'Intermediate' },
          { label: 'Beginner', value: 'Beginner' },
        ],
        placeholder: 'Select Level',
        containerClass: 'p-col-6',
      },
    ],
  },
  {
    title: 'Courses',
    iconClass: 'fa fa-file-text p-mr-2',
    name: 'courses',
    schemas: [
      {
        name: 'jobTitle',
        fieldType: 'TextInput',
        label: 'Course',
        placeholder: 'e. g. Finance Manage',
        containerClass: 'p-col-12 p-sm-6',
      },
      {
        name: 'courseInstitution',
        fieldType: 'TextInput',
        label: 'Institution',
        placeholder: 'e. g. New York Business School',
        containerClass: 'p-col-12 p-sm-6',
      },
      {
        fieldType: 'DropdownInput',
        label: 'Start Date',
        name: 'startMonth',
        options: START_MONTH,
        placeholder: "Don't Show",
        containerClass: 'p-col-6 p-md-3 ',
      },
      {
        fieldType: 'DropdownInput',
        name: 'startYear',
        options: YEAR_LIST,
        value: '2021',
        containerClass: 'p-col-6 p-md-3 p-as-end',
      },
      {
        fieldType: 'DropdownInput',
        name: 'endMonth',
        options: END_MONTH,
        placeholder: "Don't Show",
        label: 'End Date',
        containerClass: 'p-col-6 p-md-3',
      },
      {
        fieldType: 'DropdownInput',
        name: 'endYear',
        options: YEAR_LIST,
        value: '2021',
        containerClass: 'p-col-6 p-md-3 p-as-end',
      },
      {
        fieldType: 'EditorInput',
        label: 'Description',
        name: 'courseDescription',
        containerClass: 'p-col-12',
      },
    ],
  },
  {
    title: 'Achievements',
    iconClass: 'fa fa-clock-o p-mr-2',
    name: 'achievements',
    schemas: [
      {
        fieldType: 'EditorInput',
        label: 'Description',
        name: 'achievementDescription',
        containerClass: 'p-col-12',
      },
    ],
  },
];

export const TEMPLATES = ['BasicTemplate'];
